from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from app.models import utc_now_iso


class TAXII21ServerEmulator:
    """Emulates a TAXII 2.1 Server API (Discovery, Api-Root, Collections, Manifest, & Envelope delivery)."""

    def __init__(self, api_root_title: str = "Cloud Campaign Threat Intel Root") -> None:
        self.api_root_title = api_root_title
        self.api_root_path = "/taxii2/api-root"
        self.collections: Dict[str, Dict[str, Any]] = {}
        self.envelopes: Dict[str, List[Dict[str, Any]]] = {}

        # Default Collection setup
        default_coll_id = "91a7b520-2ceb-478b-aebd-47ee21074e2d"
        self.create_collection(
            collection_id=default_coll_id,
            title="Cloud Campaign Indicators & Graph Objects",
            description="Machine-readable STIX 2.1 bundles generated by Cloud Campaign Evidence Graph pipeline.",
            can_read=True,
            can_write=True,
        )

    def discovery(self) -> Dict[str, Any]:
        """TAXII 2.1 Discovery Endpoint response."""
        return {
            "title": "Cloud Threat Intelligence TAXII 2.1 Server",
            "description": "Emulated TAXII 2.1 discovery endpoint for automated CTI intake.",
            "default": f"http://127.0.0.1:8000{self.api_root_path}",
            "api_roots": [f"http://127.0.0.1:8000{self.api_root_path}"],
        }

    def api_root(self) -> Dict[str, Any]:
        """TAXII 2.1 API-Root Endpoint response."""
        return {
            "title": self.api_root_title,
            "description": "API Root for Cloud Campaign Threat Intelligence Bundles",
            "versions": ["application/taxii+json;version=2.1"],
            "max_content_length": 10485760,
        }

    def create_collection(
        self,
        collection_id: str,
        title: str,
        description: str,
        can_read: bool = True,
        can_write: bool = True,
    ) -> Dict[str, Any]:
        coll = {
            "id": collection_id,
            "title": title,
            "description": description,
            "can_read": can_read,
            "can_write": can_write,
            "media_types": ["application/stix+json;version=2.1"],
        }
        self.collections[collection_id] = coll
        self.envelopes[collection_id] = []
        return coll

    def list_collections(self) -> Dict[str, Any]:
        """TAXII 2.1 Collections Endpoint response."""
        return {"collections": list(self.collections.values())}

    def publish_stix_bundle(self, collection_id: str, stix_bundle: Dict[str, Any]) -> Dict[str, Any]:
        """TAXII 2.1 Add Objects (POST /collections/{id}/objects/) endpoint."""
        if collection_id not in self.collections:
            return {"status": "error", "message": f"Collection '{collection_id}' not found."}

        objects = stix_bundle.get("objects", [])
        status_id = str(uuid.uuid4())
        now = utc_now_iso()

        self.envelopes[collection_id].extend(objects)

        return {
            "id": status_id,
            "status": "complete",
            "request_timestamp": now,
            "total_count": len(objects),
            "success_count": len(objects),
            "failure_count": 0,
            "pending_count": 0,
            "successes": [{"id": obj.get("id")} for obj in objects],
        }

    def get_objects(self, collection_id: str) -> Dict[str, Any]:
        """TAXII 2.1 Get Objects (GET /collections/{id}/objects/) endpoint."""
        if collection_id not in self.collections:
            return {"status": "error", "message": f"Collection '{collection_id}' not found."}

        return {
            "more": False,
            "objects": self.envelopes.get(collection_id, []),
        }
